FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    python3 python3-pip \
    gdb \
    nasm \
    curl wget \
    libc6-dev \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install pwntools

RUN mkdir /glibc-2.26 && \
    cd /glibc-2.26 && \
    wget https://ftp.gnu.org/gnu/glibc/glibc-2.26.tar.gz && \
    tar xzf glibc-2.26.tar.gz && \
    cd glibc-2.26 && \
    mkdir build && cd build && \
    ../configure --prefix=/glibc-2.26/install && \
    make -j$(nproc) && make install

ENV LD_LIBRARY_PATH=/glibc-2.26/install/lib

CMD ["/bin/bash"]
