FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc-11 g++-11 \
    clang-14 \
    python3.10 python3-pip \
    gdb \
    nasm \
    qemu-system-x86 \
    curl wget git \
    libcapstone-dev \
    elfutils \
    linux-headers-generic \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install pwntools angr

RUN git clone https://github.com/pwndbg/pwndbg && \
    cd pwndbg && ./setup.sh

CMD ["/bin/bash"]
